routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group([
    'namespace' => 'Guest'
], function () {
    Route::get('/', 'IndexController@index')->name('index');

    Route::group([
        'prefix' => 'destinasi',
        'as' => 'destination.'
    ], function () {
        $this->get('/', 'DestinationController@index')->name('index');
        $this->get('/{destination}', 'DestinationController@show')->name('show');
    });

    Route::group([
        'prefix' => 'kuliner',
        'as' => 'culinary.'
    ], function () {
        $this->get('/', 'CulinaryController@index')->name('index');
        $this->get('/{culinary}', 'CulinaryController@show')->name('show');
    });

    Route::group([
        'prefix' => 'galeri',
        'as' => 'gallery.'
    ], function () {
        $this->get('/', 'GalleryController@index');
        $this->get('/{gallery}', 'GalleryController@show')->name('show');
    });
});
Route::group([
   'prefix' => 'event'
], function () {
  $this->get('/', function() {
    return view('event.index');
  });
  $this->get('/festifal-bau', function() {
    return view('article.event1');
  });
  $this->get('/jakarta-fashion', function() {
    return view('article.event2');
  });
  $this->get('/art-jog', function() {
    return view('article.event3');
  });
});

//Route::post('gallery/store', 'Admin\GalleryController@store')->middleware('guest');

Route::get('/image{src}', 'MediaController@file')->where(['src' => '.*'])->name('image');

Route::group([
   'namespace' => 'Auth'
], function () {
    // Authentication Routes...
    $this->get('login', 'LoginController@showLoginForm')->name('login');
    $this->post('login', 'LoginController@login');
    $this->post('logout', 'LoginController@logout')->name('logout');

    $this->get('admin/login', 'AdminController@showLoginForm')->name('admin.login');
    $this->post('admin/login', 'AdminController@login')->name('admin.login');

    // Registration Routes...
    $this->get('register', 'RegisterController@showRegistrationForm')->name('register');
    $this->post('register', 'RegisterController@register');

    //verification Email
    $this->get('/verifyemail/{token}', 'RegisterController@verify');

    // Password Reset Routes...
    $this->get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    $this->post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    $this->get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    $this->post('password/reset', 'ResetPasswordController@reset');
});


// Admin Route
Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => 'auth.check:admin'
], function (){
    $this->get('/', 'DashboardController@index');
    $this->get('/pengaturan', 'SettingController@index')->name('setting');
    $this->post('/pengaturan/update', 'SettingController@update')->name('setting.update');
    $this->post('/pengaturan/avatar', 'SettingController@updateAvatar')->name('setting.avatar');
    $this->get('/logout', function () {
        \Illuminate\Support\Facades\Auth::logout();
        return redirect('/');
    })->name('logout');

    $this->group([
        'prefix' => '/destinasi',
    ], function () {
        $this->get('/', 'DestinationController@index')->name('destinasi');
        $this->get('/tambah', 'DestinationController@create')->name('destinasi.create');
        $this->post('/store', 'DestinationController@store')->name('destinasi.store');
        $this->get('/{slug}/edit', 'DestinationController@edit')->name('destinasi.edit');
        $this->post('/{slug}/update', 'DestinationController@update')->name('destinasi.update');
        $this->delete('/{slug}/delete', 'DestinationController@destroy')->name('destinasi.delete');
        $this->post('/{slug}/status', 'DestinationController@status')->name('destinasi.status');
    });

    $this->group([
        'prefix' => '/galeri',
    ], function () {
        $this->get('/', 'GalleryController@index')->name('galeri');
        $this->get('/tambah', 'GalleryController@create')->name('galeri.create');
        $this->post('/store', 'GalleryController@store')->name('galeri.store');
        $this->get('/{slug}/edit', 'GalleryController@edit')->name('galeri.edit');
        $this->post('/{slug}/update', 'GalleryController@update')->name('galeri.update');
        $this->delete('/{slug}/delete', 'GalleryController@destroy')->name('galeri.delete');
        $this->post('/{slug}/status', 'GalleryController@status')->name('galeri.status');
    });

    $this->group([
        'prefix' => '/event',
    ], function () {
        $this->get('/', 'EventController@index')->name('event');
        $this->get('/tambah', 'EventController@create')->name('event.create');
        $this->post('/store', 'EventController@store')->name('event.store');
        $this->get('/{slug}/edit', 'EventController@edit')->name('event.edit');
        $this->post('/{slug}/update', 'EventController@update')->name('event.update');
        $this->delete('/{slug}/delete', 'EventController@destroy')->name('event.delete');
        $this->post('/{slug}/status', 'EventController@status')->name('event.status');
    });

    $this->group([
        'prefix' => '/kuliner',
    ], function () {
        $this->get('/', 'CulinaryController@index')->name('kuliner');
        $this->get('/tambah', 'CulinaryController@create')->name('kuliner.create');
        $this->post('/store', 'CulinaryController@store')->name('kuliner.store');
        $this->get('/{slug}/edit', 'CulinaryController@edit')->name('kuliner.edit');
        $this->post('/{slug}/update', 'CulinaryController@update')->name('kuliner.update');
        $this->delete('/{slug}/delete', 'CulinaryController@destroy')->name('kuliner.delete');
        $this->post('/{slug}/status', 'CulinaryController@status')->name('kuliner.status');
    });
});

Route::group([
    'namespace' => 'Member',
    'middleware' => 'auth.check:member',
    'prefix' => '/home',
    'as' => 'member.',
], function () {
    $this->get('/', 'DashboardController@index');
    $this->get('/pengaturan', 'SettingController@index')->name('setting');
    $this->post('/pengaturan/update', 'SettingController@update')->name('setting.update');
    $this->post('/pengaturan/avatar', 'SettingController@updateAvatar')->name('setting.avatar');
    $this->get('/logout', function () {
        \Illuminate\Support\Facades\Auth::logout();
        return redirect('/');
    })->name('logout');

    $this->group([
        'prefix' => '/destinasi',
    ], function () {
        $this->get('/', 'DestinationController@index')->name('destinasi');
        $this->get('/tambah', 'DestinationController@create')->name('destinasi.create');
        $this->post('/store', 'DestinationController@store')->name('destinasi.store');
        $this->get('/{slug}/edit', 'DestinationController@edit')->name('destinasi.edit');
        $this->post('/{slug}/update', 'DestinationController@update')->name('destinasi.update');
        $this->delete('/{slug}/delete', 'DestinationController@destroy')->name('destinasi.delete');
    });

    $this->group([
        'prefix' => '/galeri',
    ], function () {
        $this->get('/', 'GalleryController@index')->name('galeri');
        $this->get('/tambah', 'GalleryController@create')->name('galeri.create');
        $this->post('/store', 'GalleryController@store')->name('galeri.store');
        $this->get('/{slug}/edit', 'GalleryController@edit')->name('galeri.edit');
        $this->post('/{slug}/update', 'GalleryController@update')->name('galeri.update');
        $this->delete('/{slug}/delete', 'GalleryController@destroy')->name('galeri.delete');
    });

    $this->group([
        'prefix' => '/event',
    ], function () {
        $this->get('/', 'EventController@index')->name('event');
        $this->get('/tambah', 'EventController@create')->name('event.create');
        $this->post('/store', 'EventController@store')->name('event.store');
        $this->get('/{slug}/edit', 'EventController@edit')->name('event.edit');
        $this->post('/{slug}/update', 'EventController@update')->name('event.update');
        $this->delete('/{slug}/delete', 'EventController@destroy')->name('event.delete');
    });

    $this->group([
        'prefix' => '/kuliner',
    ], function () {
        $this->get('/', 'CulinaryController@index')->name('kuliner');
        $this->get('/tambah', 'CulinaryController@create')->name('kuliner.create');
        $this->post('/store', 'CulinaryController@store')->name('kuliner.store');
        $this->get('/{slug}/edit', 'CulinaryController@edit')->name('kuliner.edit');
        $this->post('/{slug}/update', 'CulinaryController@update')->name('kuliner.update');
        $this->delete('/{slug}/delete', 'CulinaryController@destroy')->name('kuliner.delete');
    });
});

app/Http/Controllers/Admin/DestinationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Jobs\Articles\CreateArticle;
use App\Jobs\Articles\DeleteArticle;
use App\Jobs\Articles\UpdateArticle;
use App\Models\Contents\Article;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class DestinationController extends Controller
{
    protected $type = 'destination';

    public function __construct()
    {
        $this->middleware('auth.check:admin');
    }

    public function index()
    {
        $destination = Article::where('type', '=', $this->type)->paginate(10);

        $data = [
            'destination' => $destination,
        ];

        return view('admin.destination.index', $data);
    }

    public function create()
    {
        return view('admin.destination.create');
    }

    /**
     * @param Request $request
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'images.*' => 'required|image|mimes:jpeg,png,jpg,gif,svg',
            'cover.*' => 'required|image|mimes:jpeg,png,jpg,gif,svg',
            'title' => 'required',
            'description' => 'required',
            'location' => 'required',
        ]);

        if ($validator->fails() == true) {
            return redirect()->back()->withErrors($validator->errors());
        }

        $request->type = $this->type;

        try {
            $this->dispatch(new CreateArticle($request));
        } catch (\Exception $exception) {
            return redirect()->back()->withErrors($exception);
        }

        return redirect()->route('admin.destinasi')->with('success', 'Destinasi berhasil dibuat');
    }

    public function edit($slug)
    {
        $destination = Article::where('type', '=', $this->type)
            ->where('slug', '=', $slug)->first();

        if ($destination->count() == 0) {
            return redirect()->route('admin.destinasi')->withErrors('Destinasi tidak ada');
        }

        $data = [
            'destination' => $destination
        ];

        return view('admin.destination.edit', $data);
    }

    public function update($slug, Request $request)
    {
        $destination = Article::where('type', '=', $this->type)
            ->where('slug', '=', $slug)->first();

        if ($destination->count() == 0) {
            return redirect()->back()->withErrors('Destinasi tidak ada');
        }

        if ($destination instanceof Article) {

            $validator = Validator::make($request->all(), [
                'title' => 'required',
                'description' => 'required',
                'location' => 'required',
            ]);

            if ($validator->fails()) {
                return redirect()->back()->withErrors([$validator->errors()]);
            }

            try {
                $update = $this->dispatch(new UpdateArticle($request, $destination));
            } catch (\Exception $exception) {
                return redirect()->back()->withErrors(['error' => $exception]);
            }

            return redirect()->route('admin.destinasi')->with('success', 'Destinasi berhasil di edit');
        }

        return redirect()->back()->withErrors('Destinasi salah');
    }

    public function destroy($slug)
    {
        $destination = Article::where('type', '=', $this->type)
            ->where('slug', '=', $slug)->first();

        if ($destination->count() == 0) {
            return redirect()->route('admin.destinasi')->withErrors(['status' => 'Destinasi tidak ada']);
        }

        try {
            $delete = $this->dispatch(new DeleteArticle($destination));
        } catch (\Exception $exception) {
            return redirect()->back()->withErrors(['error' => $exception]);
        }

        return redirect()->route('admin.destinasi')->with('success', 'Destinasi berhasil di delete');
    }

    public function status($slug ,Request $request)
    {
        $destination = Article::where('type', '=', $this->type)
            ->where('slug', '=', $slug)->first();

        try {
            $destination->status = $request->status;
            $destination->save();
        } catch (\Exception $exception) {
            return back()->withErrors(['error' => $exception]);
        }

        return redirect()->route('admin.destinasi')->with('success', 'Status berhasil di perbarui');
    }
}

app/Http/Controllers/Guest/DestinationController.php
<?php
/**
 * Created by PhpStorm.
 * User: ANDROMEDA
 * Date: 4/19/2018
 * Time: 7:25 PM
 */

namespace App\Http\Controllers\Guest;

use App\Http\Controllers\Controller;
use App\Models\Contents\Article;

class DestinationController extends Controller
{
    protected $type = 'destination';

    public function index()
    {
        $culinary = Article::where('type', '=', $this->type)->get();

        $data = [
            'destination' => $culinary
        ];

        return view('destination.index', $data);
    }

    public function show($destination)
    {
        try {
            $destination = Article::where('type', '=', $this->type)->where('slug', '=', $destination)->first();
        } catch (\Exception $exception) {
            return back()->withErrors('Destinasi tidak ada
            ');
        }

        $geo = explode(',', $destination->geo_location);

        $data = [
            'destination' => $destination,
            'position' => $geo,
        ];

        return view('destination.show', $data);
    }
}

resources/views/admin/destination/create.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="container" style="float:left">
        <div class="content" style="float:left; width:100%; padding: 0px 4px 20px 0px;">
            <h2 style="margin-left:22px">Buat Destinasi</h2>
            @foreach($errors->all() as $error)
                <div class="notification">
                    <div class="alert alert-danger">
                        {{ $error }}
                    </div>
                </div>
            @endforeach
            <form class="form" action="{{ Route('admin.destinasi.store') }}" method="post"
                  enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="group">
                    <label for="cover.0">Foto Sampul <span class="required">*</span></label>
                    <input id="cover.0" class="input-field input-field-long" type="file" name="cover[]" required>
                    <label for="title">Judul <span class="required">*</span></label>
                    <input id="title" class="input-field input-field-long" type="text" name="title" required>
                </div>
                <div class="group">
                    <label for="location">Lokasi <span class="required">*</span></label>
                    <input id="location" class="input-field input-field-long" type="text" name="location">
                </div>
                <div class="group">
                    <label for="images.0">Gambar <span class="required">*</span></label>
                    <input id="images.0" class="input-field input-field-long" type="file" name="images[]" multiple required>
                </div>
                <div class="group-full">
                  <label for="description">Deskripsi <span class="required">*</span></label>
                  <textarea name="description" id="description" class="input-field input-field-long"
                            required></textarea>
                </div>
                <div class="group-full" style="text-align: center; margin-top:12px;">
                    <button class="btn green" type="submit">Simpan</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/destination/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: ANDROMEDA
 * Date: 3/27/2018
 * Time: 10:40 AM
 */

?>

@extends('admin.layouts.app')
@section('content')
    <div class="container">
        <div class="content" style="float:left; padding: 0; width:100%">
            <h2 style="margin-left:22px">Edit Destinasi</h2>
            @foreach($errors->all() as $error)
                <div class="notification">
                    <div class="alert alert-danger">
                        {{ $error }}
                    </div>
                </div>
            @endforeach
            <form class="form" action="{{ Route('admin.destinasi.update', $destination->slug) }}" method="post">
                {{ csrf_field() }}
                <div class="group">
                    <label for="title">Judul <span class="required">*</span></label>
                    <input id="title" class="input-field input-field-long" type="text" name="title"
                           value="{{ $destination->title }}" required>
                    <label for="description">Deskripsi <span class="required">*</span></label>
                    <textarea name="description" id="description" class="input-field input-field-long"
                              required>{{ $destination->description }}</textarea>
                </div>
                <div class="group">
                    <label for="location">Lokasi <span class="required">*</span></label>
                    <input id="location" class="input-field input-field-long" type="text"
                           value="{{ $destination->location }}" name="location" required>
                </div>
                <div class="group">
                    <button class="btn green" type="submit" style="text-align: center">Edit</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/destination/index.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="container">
        <div class="content content-table">
            @if(session('success'))
                <div class="notification">
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                </div>
            @endif
            <div class="top">
                <span style="float:left"><h1>Destinasi</h1></span>
                <a href="{{ route('admin.destinasi.create') }}" class="btn btn-small blue"
                   style="margin: 20px; float:left">Tambah</a>
            </div>
            <table class="table">
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Status</th>
                    <th>Author</th>
                    <th>Gambar</th>
                    <th>Aksi</th>
                </tr>
                @foreach($destination as $key => $value)
                    <tr>
                        <td>{{ $key+1 }}</td>
                        <td>{{ $value->title }}</td>
                        <td>
                            <button id="status" value="{{ $value->slug }}"> {{ $value->status }}</button>
                        </td>
                        <td>{{ $value->user->name }}</td>
                        <td>{{ $value->media()->count() }}</td>
                        <td width="255">
                            <a href="{{ route('admin.destinasi.edit', $value->slug) }}" class="btn blue"
                               style="float:left">Edit</a>
                            <a href="#" class="btn green" style="float:left; margin-left:5px">Lihat</a>
                            <span style="float:left; margin-left:5px">
                          <form class="" action="{{ route('admin.destinasi.delete', $value->slug) }}" method="post">
                              {{ csrf_field() }}
                              {{ method_field('DELETE') }}
                              <button type="submit" class="btn red">Hapus</button>
                          </form>
                        </span>
                        </td>
                    </tr>
                @endforeach
            </table>
            {{ $destination->links('vendor.pagination.paging') }}
        </div>
    </div>
    <!-- The Modal -->
    <div class="modal" id="modal">
        <div class="modalDialog">
            <section class="modalContent">
                <header class="modalHeader">
                    <h2 class="modalTitle">Edit Status</h2>
                    <a href="#" id="modalClose" class="modalClose">&times;</a>
                </header>
                <div class="modalBody">
                    <div class="modalText">
                        <form id="form-status" action="#" method="post" style="text-align: center">
                            {{ csrf_field() }}
                            <div>
                                <label for="status" style="margin-right: 1rem">Status</label>
                                <select name="status" id="status" style="color: #151515; margin-bottom: 1rem">
                                    <option value="published">Publish</option>
                                    <option value="pending">Pending</option>
                                </select>
                            </div>
                            <div>
                                <button type="submit" class="btn green">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript">
        $(document).ready(function () {
            var slug = null;

            $('button#status').click(function (e) {
                e.preventDefault();
                slug = $(this).attr('value');

                var str = "{{ route('admin.destinasi.status', 'slug') }}";
                var url = str.replace("slug", slug);

                $('form#form-status').attr('action', url);
                $('#modal').css('display', 'block');
            });
            $('a#modalClose').click(function (e) {
                e.preventDefault();
                $('#modal').css('display', 'none');
            });
        });
    </script>
@endsection