routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group([
    'namespace' => 'Guest'
], function () {
    Route::get('/', 'IndexController@index')->name('index');

    Route::group([
        'prefix' => 'destinasi',
        'as' => 'destination.'
    ], function () {
        $this->get('/', 'DestinationController@index')->name('index');
        $this->get('/{destination}', 'DestinationController@show')->name('show');
    });

    Route::group([
        'prefix' => 'kuliner',
        'as' => 'culinary.'
    ], function () {
        $this->get('/', 'CulinaryController@index')->name('index');
        $this->get('/{culinary}', 'CulinaryController@show')->name('show');
    });

    Route::group([
        'prefix' => 'galeri',
        'as' => 'gallery.'
    ], function () {
        $this->get('/', 'GalleryController@index');
        $this->get('/{gallery}', 'GalleryController@show')->name('show');
    });
});
Route::group([
   'prefix' => 'event'
], function () {
  $this->get('/', function() {
    return view('event.index');
  });
  $this->get('/festifal-bau', function() {
    return view('article.event1');
  });
  $this->get('/jakarta-fashion', function() {
    return view('article.event2');
  });
  $this->get('/art-jog', function() {
    return view('article.event3');
  });
});

//Route::post('gallery/store', 'Admin\GalleryController@store')->middleware('guest');

Route::get('/image{src}', 'MediaController@file')->where(['src' => '.*'])->name('image');

Route::group([
   'namespace' => 'Auth'
], function () {
    // Authentication Routes...
    $this->get('login', 'LoginController@showLoginForm')->name('login');
    $this->post('login', 'LoginController@login');
    $this->post('logout', 'LoginController@logout')->name('logout');

    $this->get('admin/login', 'AdminController@showLoginForm')->name('admin.login');
    $this->post('admin/login', 'AdminController@login')->name('admin.login');

    // Registration Routes...
    $this->get('register', 'RegisterController@showRegistrationForm')->name('register');
    $this->post('register', 'RegisterController@register');

    //verification Email
    $this->get('/verifyemail/{token}', 'RegisterController@verify');

    // Password Reset Routes...
    $this->get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    $this->post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    $this->get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    $this->post('password/reset', 'ResetPasswordController@reset');
});


// Admin Route
Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => 'auth.check:admin'
], function (){
    $this->get('/', 'DashboardController@index');
    $this->get('/pengaturan', 'SettingController@index')->name('setting');
    $this->post('/pengaturan/update', 'SettingController@update')->name('setting.update');
    $this->post('/pengaturan/avatar', 'SettingController@updateAvatar')->name('setting.avatar');
    $this->get('/logout', function () {
        \Illuminate\Support\Facades\Auth::logout();
        return redirect('/');
    })->name('logout');

    $this->group([
        'prefix' => '/destinasi',
    ], function () {
        $this->get('/', 'DestinationController@index')->name('destinasi');
        $this->get('/tambah', 'DestinationController@create')->name('destinasi.create');
        $this->post('/store', 'DestinationController@store')->name('destinasi.store');
        $this->get('/{slug}/edit', 'DestinationController@edit')->name('destinasi.edit');
        $this->post('/{slug}/update', 'DestinationController@update')->name('destinasi.update');
        $this->delete('/{slug}/delete', 'DestinationController@destroy')->name('destinasi.delete');
        $this->post('/{slug}/status', 'DestinationController@status')->name('destinasi.status');
    });

    $this->group([
        'prefix' => '/galeri',
    ], function () {
        $this->get('/', 'GalleryController@index')->name('galeri');
        $this->get('/tambah', 'GalleryController@create')->name('galeri.create');
        $this->post('/store', 'GalleryController@store')->name('galeri.store');
        $this->get('/{slug}/edit', 'GalleryController@edit')->name('galeri.edit');
        $this->post('/{slug}/update', 'GalleryController@update')->name('galeri.update');
        $this->delete('/{slug}/delete', 'GalleryController@destroy')->name('galeri.delete');
        $this->post('/{slug}/status', 'GalleryController@status')->name('galeri.status');
    });

    $this->group([
        'prefix' => '/event',
    ], function () {
        $this->get('/', 'EventController@index')->name('event');
        $this->get('/tambah', 'EventController@create')->name('event.create');
        $this->post('/store', 'EventController@store')->name('event.store');
        $this->get('/{slug}/edit', 'EventController@edit')->name('event.edit');
        $this->post('/{slug}/update', 'EventController@update')->name('event.update');
        $this->delete('/{slug}/delete', 'EventController@destroy')->name('event.delete');
        $this->post('/{slug}/status', 'EventController@status')->name('event.status');
    });

    $this->group([
        'prefix' => '/kuliner',
    ], function () {
        $this->get('/', 'CulinaryController@index')->name('kuliner');
        $this->get('/tambah', 'CulinaryController@create')->name('kuliner.create');
        $this->post('/store', 'CulinaryController@store')->name('kuliner.store');
        $this->get('/{slug}/edit', 'CulinaryController@edit')->name('kuliner.edit');
        $this->post('/{slug}/update', 'CulinaryController@update')->name('kuliner.update');
        $this->delete('/{slug}/delete', 'CulinaryController@destroy')->name('kuliner.delete');
        $this->post('/{slug}/status', 'CulinaryController@status')->name('kuliner.status');
    });
});

Route::group([
    'namespace' => 'Member',
    'middleware' => 'auth.check:member',
    'prefix' => '/home',
    'as' => 'member.',
], function () {
    $this->get('/', 'DashboardController@index');
    $this->get('/pengaturan', 'SettingController@index')->name('setting');
    $this->post('/pengaturan/update', 'SettingController@update')->name('setting.update');
    $this->post('/pengaturan/avatar', 'SettingController@updateAvatar')->name('setting.avatar');
    $this->get('/logout', function () {
        \Illuminate\Support\Facades\Auth::logout();
        return redirect('/');
    })->name('logout');

    $this->group([
        'prefix' => '/destinasi',
    ], function () {
        $this->get('/', 'DestinationController@index')->name('destinasi');
        $this->get('/tambah', 'DestinationController@create')->name('destinasi.create');
        $this->post('/store', 'DestinationController@store')->name('destinasi.store');
        $this->get('/{slug}/edit', 'DestinationController@edit')->name('destinasi.edit');
        $this->post('/{slug}/update', 'DestinationController@update')->name('destinasi.update');
        $this->delete('/{slug}/delete', 'DestinationController@destroy')->name('destinasi.delete');
    });

    $this->group([
        'prefix' => '/galeri',
    ], function () {
        $this->get('/', 'GalleryController@index')->name('galeri');
        $this->get('/tambah', 'GalleryController@create')->name('galeri.create');
        $this->post('/store', 'GalleryController@store')->name('galeri.store');
        $this->get('/{slug}/edit', 'GalleryController@edit')->name('galeri.edit');
        $this->post('/{slug}/update', 'GalleryController@update')->name('galeri.update');
        $this->delete('/{slug}/delete', 'GalleryController@destroy')->name('galeri.delete');
    });

    $this->group([
        'prefix' => '/event',
    ], function () {
        $this->get('/', 'EventController@index')->name('event');
        $this->get('/tambah', 'EventController@create')->name('event.create');
        $this->post('/store', 'EventController@store')->name('event.store');
        $this->get('/{slug}/edit', 'EventController@edit')->name('event.edit');
        $this->post('/{slug}/update', 'EventController@update')->name('event.update');
        $this->delete('/{slug}/delete', 'EventController@destroy')->name('event.delete');
    });

    $this->group([
        'prefix' => '/kuliner',
    ], function () {
        $this->get('/', 'CulinaryController@index')->name('kuliner');
        $this->get('/tambah', 'CulinaryController@create')->name('kuliner.create');
        $this->post('/store', 'CulinaryController@store')->name('kuliner.store');
        $this->get('/{slug}/edit', 'CulinaryController@edit')->name('kuliner.edit');
        $this->post('/{slug}/update', 'CulinaryController@update')->name('kuliner.update');
        $this->delete('/{slug}/delete', 'CulinaryController@destroy')->name('kuliner.delete');
    });
});

resources/views/admin/index.blade.php
@extends('admin.layouts.app')
@section('header')
@endsection
@section('content')
    <div class="container">
        @if (session('status'))
            <div class="notification">
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            </div>
        @endif
        <div class="count-box">
            <div class="top">
                {{ $destination }}
            </div>
            <div class="bottom blue">
                Destinasi
                <a href="{{ route('admin.destinasi.create') }}" class="btn white">Tambah</a>
                <a href="{{ route('admin.destinasi') }}" class="btn white">List</a>
            </div>
        </div>
        <div class="count-box">
            <div class="top">
                {{ $gallery }}
            </div>
            <div class="bottom green">
                Galeri
                <a href="{{ route('admin.galeri.create') }}" class="btn white">Tambah</a>
                <a href="{{ route('admin.galeri') }}" class="btn white">List</a>
            </div>
        </div>
        <div class="count-box">
            <div class="top">
                {{ $culinary }}
            </div>
            <div class="bottom red">
                Kuliner
                <a href="{{ route('admin.kuliner.create') }}" class="btn white">Tambah</a>
                <a href="{{ route('admin.kuliner') }}" class="btn white">List</a>
            </div>
        </div>
        <div class="count-box">
            <div class="top">
                {{ $event }}
            </div>
            <div class="bottom red">
                Event
                <a href="{{ route('admin.event.create') }}" class="btn white">Tambah</a>
                <a href="{{ route('admin.event') }}" class="btn white">List</a>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/settings.blade.php
@extends('admin.layouts.app')
@section('header')
    <style media="screen">
        .container {
            margin-top: 60px;
        }

        .box {
            position: absolute;
            left: 0;
            right: 0;
            margin-left: auto;
            margin-right: auto;
            width: 600px;
            height: auto;
            background: white;
        }

        .box h1 {
            text-align: center;
            margin: 0;
            padding: 12px 0px;
        }

        .avatar img {
            width: 50%;
            margin: 20px 25%;
            height: auto;
            border-radius: 999px;
        }

        .info-body {
            padding: 0 30px;
        }
    </style>
@endsection
@section('content')
    <div class="container">
        <div class="box">
            <h1 class="blue">Pengaturan Akun</h1>
            @if(session('success'))
                <div class="notification" style="margin: auto;">
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                </div>
            @endif
            <div class="avatar">
                <img
                        @if($user->media()->count() == 0)
                            src="{{ asset('img/avatar.png') }}"
                        @else
                            src="{{ route('image', $user->media->first()->src) }}"
                        @endif
                >
                <form class="form" action="{{ route('admin.setting.avatar') }}" method="post" style="width: 50%; margin: 0px 25%; text-align:center" enctype="multipart/form-data">
                    @csrf
                    <label for="avatar">Ganti Avatar</label>
                    <input id="avatar"
                           class="input-field input-field-long {{ $errors->has('avatar') ? ' is-invalid' : '' }}"
                           type="file" name="avatar[]" value="{{ old('avatar') }}" required autofocus>
                    @if ($errors->has('avatar'))
                        <span class="invalid-feedback">
                <strong>{{ $errors->first('avatar') }}</strong>
            </span>
                    @endif
                    <button class="btn blue" type="submit">Submit</button>
                </form>
            </div>
            <div class="info-body">
                <form class="form" method="post" action="{{ route('admin.setting.update') }}">
                    @csrf
                    <label for="name">Nama</label>
                    <input id="name"
                           class="input-field input-field-long {{ $errors->has('name') ? ' is-invalid' : '' }}"
                           type="text" name="name" value="{{ $user->name or old('name') }}" required autofocus>
                    @if ($errors->has('name'))
                        <span class="invalid-feedback">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
                    @endif
                    <label for="username">Username</label>
                    <input id="username"
                           class="input-field input-field-long {{ $errors->has('username') ? ' is-invalid' : '' }}"
                           type="text" name="username" value="{{ $user->username or old('username') }}" required>
                    @if ($errors->has('username'))
                        <span class="invalid-feedback">
                <strong>{{ $errors->first('username') }}</strong>
            </span>
                    @endif
                    <label for="email">Email</label>
                    <input id="email"
                           class="input-field input-field-long {{ $errors->has('email') ? ' is-invalid' : '' }}"
                           type="email" name="email" value="{{ $user->email or old('email') }}" required>
                    @if ($errors->has('email'))
                        <span class="invalid-feedback">
                <strong>{{ $errors->first('email') }}</strong>
            </span>
                    @endif
                    <label for="password">Password</label>
                    <input id="password"
                           class="input-field input-field-long {{ $errors->has('password') ? ' is-invalid' : '' }}"
                           type="password" name="password" value="{{ old('password') }}" required>
                    @if ($errors->has('password'))
                        <span class="invalid-feedback">
                <strong>{{ $errors->first('password') }}</strong>
            </span>
                    @endif
                    <button class="btn green" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection