routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group([
    'namespace' => 'Guest'
], function () {
    Route::get('/', 'IndexController@index')->name('index');

    Route::group([
        'prefix' => 'destinasi',
        'as' => 'destination.'
    ], function () {
        $this->get('/', 'DestinationController@index')->name('index');
        $this->get('/{destination}', 'DestinationController@show')->name('show');
    });

    Route::group([
        'prefix' => 'kuliner',
        'as' => 'culinary.'
    ], function () {
        $this->get('/', 'CulinaryController@index')->name('index');
        $this->get('/{culinary}', 'CulinaryController@show')->name('show');
    });

    Route::group([
        'prefix' => 'galeri',
        'as' => 'gallery.'
    ], function () {
        $this->get('/', 'GalleryController@index');
        $this->get('/{gallery}', 'GalleryController@show')->name('show');
    });
});
Route::group([
   'prefix' => 'event'
], function () {
  $this->get('/', function() {
    return view('event.index');
  });
  $this->get('/festifal-bau', function() {
    return view('article.event1');
  });
  $this->get('/jakarta-fashion', function() {
    return view('article.event2');
  });
  $this->get('/art-jog', function() {
    return view('article.event3');
  });
});

//Route::post('gallery/store', 'Admin\GalleryController@store')->middleware('guest');

Route::get('/image{src}', 'MediaController@file')->where(['src' => '.*'])->name('image');

Route::group([
   'namespace' => 'Auth'
], function () {
    // Authentication Routes...
    $this->get('login', 'LoginController@showLoginForm')->name('login');
    $this->post('login', 'LoginController@login');
    $this->post('logout', 'LoginController@logout')->name('logout');

    $this->get('admin/login', 'AdminController@showLoginForm')->name('admin.login');
    $this->post('admin/login', 'AdminController@login')->name('admin.login');

    // Registration Routes...
    $this->get('register', 'RegisterController@showRegistrationForm')->name('register');
    $this->post('register', 'RegisterController@register');

    //verification Email
    $this->get('/verifyemail/{token}', 'RegisterController@verify');

    // Password Reset Routes...
    $this->get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    $this->post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    $this->get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    $this->post('password/reset', 'ResetPasswordController@reset');
});


// Admin Route
Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => 'auth.check:admin'
], function (){
    $this->get('/', 'DashboardController@index');
    $this->get('/pengaturan', 'SettingController@index')->name('setting');
    $this->post('/pengaturan/update', 'SettingController@update')->name('setting.update');
    $this->post('/pengaturan/avatar', 'SettingController@updateAvatar')->name('setting.avatar');
    $this->get('/logout', function () {
        \Illuminate\Support\Facades\Auth::logout();
        return redirect('/');
    })->name('logout');

    $this->group([
        'prefix' => '/destinasi',
    ], function () {
        $this->get('/', 'DestinationController@index')->name('destinasi');
        $this->get('/tambah', 'DestinationController@create')->name('destinasi.create');
        $this->post('/store', 'DestinationController@store')->name('destinasi.store');
        $this->get('/{slug}/edit', 'DestinationController@edit')->name('destinasi.edit');
        $this->post('/{slug}/update', 'DestinationController@update')->name('destinasi.update');
        $this->delete('/{slug}/delete', 'DestinationController@destroy')->name('destinasi.delete');
        $this->post('/{slug}/status', 'DestinationController@status')->name('destinasi.status');
    });

    $this->group([
        'prefix' => '/galeri',
    ], function () {
        $this->get('/', 'GalleryController@index')->name('galeri');
        $this->get('/tambah', 'GalleryController@create')->name('galeri.create');
        $this->post('/store', 'GalleryController@store')->name('galeri.store');
        $this->get('/{slug}/edit', 'GalleryController@edit')->name('galeri.edit');
        $this->post('/{slug}/update', 'GalleryController@update')->name('galeri.update');
        $this->delete('/{slug}/delete', 'GalleryController@destroy')->name('galeri.delete');
        $this->post('/{slug}/status', 'GalleryController@status')->name('galeri.status');
    });

    $this->group([
        'prefix' => '/event',
    ], function () {
        $this->get('/', 'EventController@index')->name('event');
        $this->get('/tambah', 'EventController@create')->name('event.create');
        $this->post('/store', 'EventController@store')->name('event.store');
        $this->get('/{slug}/edit', 'EventController@edit')->name('event.edit');
        $this->post('/{slug}/update', 'EventController@update')->name('event.update');
        $this->delete('/{slug}/delete', 'EventController@destroy')->name('event.delete');
        $this->post('/{slug}/status', 'EventController@status')->name('event.status');
    });

    $this->group([
        'prefix' => '/kuliner',
    ], function () {
        $this->get('/', 'CulinaryController@index')->name('kuliner');
        $this->get('/tambah', 'CulinaryController@create')->name('kuliner.create');
        $this->post('/store', 'CulinaryController@store')->name('kuliner.store');
        $this->get('/{slug}/edit', 'CulinaryController@edit')->name('kuliner.edit');
        $this->post('/{slug}/update', 'CulinaryController@update')->name('kuliner.update');
        $this->delete('/{slug}/delete', 'CulinaryController@destroy')->name('kuliner.delete');
        $this->post('/{slug}/status', 'CulinaryController@status')->name('kuliner.status');
    });
});

Route::group([
    'namespace' => 'Member',
    'middleware' => 'auth.check:member',
    'prefix' => '/home',
    'as' => 'member.',
], function () {
    $this->get('/', 'DashboardController@index');
    $this->get('/pengaturan', 'SettingController@index')->name('setting');
    $this->post('/pengaturan/update', 'SettingController@update')->name('setting.update');
    $this->post('/pengaturan/avatar', 'SettingController@updateAvatar')->name('setting.avatar');
    $this->get('/logout', function () {
        \Illuminate\Support\Facades\Auth::logout();
        return redirect('/');
    })->name('logout');

    $this->group([
        'prefix' => '/destinasi',
    ], function () {
        $this->get('/', 'DestinationController@index')->name('destinasi');
        $this->get('/tambah', 'DestinationController@create')->name('destinasi.create');
        $this->post('/store', 'DestinationController@store')->name('destinasi.store');
        $this->get('/{slug}/edit', 'DestinationController@edit')->name('destinasi.edit');
        $this->post('/{slug}/update', 'DestinationController@update')->name('destinasi.update');
        $this->delete('/{slug}/delete', 'DestinationController@destroy')->name('destinasi.delete');
    });

    $this->group([
        'prefix' => '/galeri',
    ], function () {
        $this->get('/', 'GalleryController@index')->name('galeri');
        $this->get('/tambah', 'GalleryController@create')->name('galeri.create');
        $this->post('/store', 'GalleryController@store')->name('galeri.store');
        $this->get('/{slug}/edit', 'GalleryController@edit')->name('galeri.edit');
        $this->post('/{slug}/update', 'GalleryController@update')->name('galeri.update');
        $this->delete('/{slug}/delete', 'GalleryController@destroy')->name('galeri.delete');
    });

    $this->group([
        'prefix' => '/event',
    ], function () {
        $this->get('/', 'EventController@index')->name('event');
        $this->get('/tambah', 'EventController@create')->name('event.create');
        $this->post('/store', 'EventController@store')->name('event.store');
        $this->get('/{slug}/edit', 'EventController@edit')->name('event.edit');
        $this->post('/{slug}/update', 'EventController@update')->name('event.update');
        $this->delete('/{slug}/delete', 'EventController@destroy')->name('event.delete');
    });

    $this->group([
        'prefix' => '/kuliner',
    ], function () {
        $this->get('/', 'CulinaryController@index')->name('kuliner');
        $this->get('/tambah', 'CulinaryController@create')->name('kuliner.create');
        $this->post('/store', 'CulinaryController@store')->name('kuliner.store');
        $this->get('/{slug}/edit', 'CulinaryController@edit')->name('kuliner.edit');
        $this->post('/{slug}/update', 'CulinaryController@update')->name('kuliner.update');
        $this->delete('/{slug}/delete', 'CulinaryController@destroy')->name('kuliner.delete');
    });
});

app/Http/Controllers/Admin/GalleryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Jobs\Contents\CreateContent;
use App\Jobs\Contents\DeleteContent;
use App\Jobs\Contents\UpdateContent;
use App\Models\Contents\Content;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class GalleryController extends Controller
{
    protected $type = 'gallery';

    public function __construct()
    {
        $this->middleware('auth.check:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $gallery = Content::where('type', '=', $this->type)->paginate(10);

        $data = [
            'gallery' => $gallery
        ];

        return view('admin.gallery.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.gallery.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'description' => 'required',
            'images.*' => 'required|image|mimes:jpeg,png,jpg,gif,svg',
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator->errors());
        }

        $request->type = $this->type;

        try {
            $create = $this->dispatch(new CreateContent($request));
        } catch (\Exception $exception) {
            return redirect()->back()->withErrors($exception);
        }

        return redirect()->route('admin.galeri')->with('success', 'Galeri berhasil dibuat');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        $gallery = Content::where('type', '=', $this->type)
            ->where('slug', '=', $slug)->first();

        if ($gallery->count() == 0) {
            return redirect()->route('admin.galeri')->withErrors(['status' => 'Galeri tidak ada']);
        }

        $data = [
            'gallery' => $gallery
        ];

        return view('admin.gallery.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $slug)
    {
        $gallery = Content::where('type', '=', $this->type)
            ->where('slug', '=', $slug)->first();

        if ($gallery->count() == 0) {
            return redirect()->route('admin.galeri')->withErrors('Galeri tidak ada');
        }

        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'description' => 'required',
            'date_start.*' => 'required|string',
        ]);

        if ($validator->fails()) {
            return back()->with($validator->errors());
        }

        try {
            $this->dispatch(new UpdateContent($request, $gallery));
        } catch (\Exception $exception) {
            return redirect()->back()->withErrors($exception);
        }

        return redirect()->route('admin.galeri')->with('success', 'Galeri berhasil di edit');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($slug)
    {
        $gallery = Content::where('type', '=', $this->type)
            ->where('slug', '=', $slug)->first();

        if ($gallery->count() == 0) {
            return redirect()->route('admin.galeri')->withErrors('Galeri tidak ada');
        }

        try {
            $this->dispatch(new DeleteContent($gallery));
        } catch (\Exception $exception) {
            return redirect()->back()->withErrors($exception);
        }

        return redirect()->route('admin.galeri')->with('success', $gallery->title . ' berhasil dihapus');
    }

    public function status($slug, Request $request)
    {
        $gallery = Content::where('type', '=', $this->type)
            ->where('slug', '=', $slug)->first();

        try {
            $gallery->status = $request->status;
            $gallery->save();
        } catch (\Exception $exception) {
            return back()->withErrors(['error' => $exception]);
        }

        return redirect()->route('admin.galeri')->with('success', 'Status telah diperbarui');
    }
}

app/Http/Controllers/Guest/GalleryController.php
<?php
/**
 * Created by PhpStorm.
 * User: ANDROMEDA
 * Date: 4/19/2018
 * Time: 10:05 PM
 */

namespace App\Http\Controllers\Guest;


use App\Http\Controllers\Controller;
use App\Models\Contents\Content;

class GalleryController extends Controller
{
    protected $type = 'gallery';

    public function index()
    {
        $culinary = Content::where('type', '=', $this->type)->get();

        $data = [
            'gallery' => $culinary
        ];

        return view('gallery.index', $data);
    }

    public function show($gallery)
    {
        try {
            $destination = Content::where('type', '=', $this->type)->where('slug', '=', $gallery)->first();
        } catch (\Exception $exception) {
            return back()->withErrors('Destinasi tidak ada
            ');
        }

        $data = [
            'gallery' => $destination,
        ];

        return view('gallery.show', $data);
    }
}

resources/views/admin/gallery/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: ANDROMEDA
 * Date: 4/3/2018
 * Time: 8:32 PM
 */
?>
@extends('admin.layouts.app')
@section('content')
    <div class="container">
        <div class="content" style="float:left; padding: 0; width:100%; padding: 0px 4px 20px 0px;">
            <h2 style="margin-left:22px">Buat Galeri</h2>
            @foreach($errors->all() as $error)
                <div class="notification">
                    <div class="alert alert-danger">
                        {{ $error }}
                    </div>
                </div>
            @endforeach
            <form class="form" action="{{ Route('admin.galeri.store') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="group">
                    <label for="title">Judul <span class="required">*</span></label>
                    <input id="title" class="input-field input-field-long" type="text" name="title" required>
                    <label for="description">Deskripsi <span class="required">*</span></label>
                    <textarea name="description" id="description" class="input-field input-field-long"
                              required></textarea>
                </div>
                <div class="group-full">
                    <label for="images.0">Gambar <span class="required">*</span></label>
                    <input id="images.0" class="input-field" type="file" name="images[]" multiple required>
                </div>
                <div class="group-full" style="text-align:center;">
                    <button class="btn green" type="submit" style="margin-top:12px;">Simpan</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/gallery/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: ANDROMEDA
 * Date: 4/3/2018
 * Time: 8:32 PM
 */
?>
@extends('admin.layouts.app')
@section('content')
    <div class="container">
        <div class="content" style="float:left; padding: 0; width:100%">
            <h2 style="margin-left:22px">Edit Galeri</h2>
            @foreach($errors->all() as $error)
                <div class="notification">
                    <div class="alert alert-danger">
                        {{ $error }}
                    </div>
                </div>
            @endforeach
            <form class="form" action="{{ Route('admin.galeri.update', $gallery->slug) }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="group">
                    <label for="title">Judul <span class="required">*</span></label>
                    <input id="title" class="input-field input-field-long" type="text" name="title"
                           value="{{ $gallery->title }}" required>
                    <label for="description">Deskripsi <span class="required">*</span></label>
                    <textarea name="description" id="description" class="input-field input-field-long"
                              required>{{ $gallery->description }}</textarea>
                </div>
                <div class="group">
                    <button class="btn green" type="submit" style="text-align: center">Save</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/gallery/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: ANDROMEDA
 * Date: 4/3/2018
 * Time: 8:25 PM
 */
?>
@extends('admin.layouts.app')
@section('content')
    <div class="container">
        <div class="content content-table">
            @if(session('success'))
                <div class="notification">
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                </div>
            @endif
            <div class="top">
                <span style="float:left"><h1>Galeri</h1></span>
                <a href="{{ route('admin.galeri.create') }}" class="btn btn-small blue"
                   style="margin: 20px; float:left">Tambah</a>
            </div>
            <table class="table">
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Status</th>
                    <th>Author</th>
                    <th>Gambar</th>
                    <th>Aksi</th>
                </tr>
                @foreach($gallery as $key => $value)
                    <tr>
                        <td>{{ $key+1 }}</td>
                        <td>{{ $value->title }}</td>
                        <td>
                            <button id="status" value="{{ $value->slug }}"> {{ $value->status }}</button>
                        </td>
                        <td>{{ $value->user->name }}</td>
                        <td>{{ $value->media()->count() }}</td>
                        <td width="255">
                            <a href="{{ route('admin.galeri.edit', $value->slug) }}" class="btn blue"
                               style="float:left">Edit</a>
                            <a href="#" class="btn green" style="float:left; margin-left:5px">Lihat</a>
                            <span style="float:left; margin-left:5px">
                          <form class="" action="{{ route('admin.galeri.delete', $value->slug) }}" method="post">
                              {{ csrf_field() }}
                              {{ method_field('DELETE') }}
                              <button type="submit" class="btn red">Hapus</button>
                          </form>
                        </span>
                        </td>
                    </tr>
                @endforeach
            </table>
            {{ $gallery->links('vendor.pagination.paging') }}
        </div>
    </div>
    <!-- The Modal -->
    <div class="modal" id="modal">
        <div class="modalDialog">
            <section class="modalContent">
                <header class="modalHeader">
                    <h2 class="modalTitle">Edit Status</h2>
                    <a href="#" id="modalClose" class="modalClose">&times;</a>
                </header>
                <div class="modalBody">
                    <div class="modalText">
                        <form id="form-status" action="#" method="post" style="text-align: center">
                            {{ csrf_field() }}
                            <div>
                                <label for="status" style="margin-right: 1rem">Status</label>
                                <select name="status" id="status" style="color: #151515; margin-bottom: 1rem">
                                    <option value="published">Publish</option>
                                    <option value="pending">Pending</option>
                                </select>
                            </div>
                            <div>
                                <button type="submit" class="btn green">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript">
        $(document).ready(function () {
            var slug = null;

            $('button#status').click(function (e) {
                e.preventDefault();
                slug = $(this).attr('value');

                var str = "{{ route('admin.galeri.status', 'slug') }}";
                var url = str.replace("slug", slug);

                $('form#form-status').attr('action', url);
                $('#modal').css('display', 'block');
            });
            $('a#modalClose').click(function (e) {
                e.preventDefault();
                $('#modal').css('display', 'none');
            });
        });
    </script>
@endsection