routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group([
    'namespace' => 'Guest'
], function () {
    Route::get('/', 'IndexController@index')->name('index');

    Route::group([
        'prefix' => 'destinasi',
        'as' => 'destination.'
    ], function () {
        $this->get('/', 'DestinationController@index')->name('index');
        $this->get('/{destination}', 'DestinationController@show')->name('show');
    });

    Route::group([
        'prefix' => 'kuliner',
        'as' => 'culinary.'
    ], function () {
        $this->get('/', 'CulinaryController@index')->name('index');
        $this->get('/{culinary}', 'CulinaryController@show')->name('show');
    });

    Route::group([
        'prefix' => 'galeri',
        'as' => 'gallery.'
    ], function () {
        $this->get('/', 'GalleryController@index');
        $this->get('/{gallery}', 'GalleryController@show')->name('show');
    });
});
Route::group([
   'prefix' => 'event'
], function () {
  $this->get('/', function() {
    return view('event.index');
  });
  $this->get('/festifal-bau', function() {
    return view('article.event1');
  });
  $this->get('/jakarta-fashion', function() {
    return view('article.event2');
  });
  $this->get('/art-jog', function() {
    return view('article.event3');
  });
});

//Route::post('gallery/store', 'Admin\GalleryController@store')->middleware('guest');

Route::get('/image{src}', 'MediaController@file')->where(['src' => '.*'])->name('image');

Route::group([
   'namespace' => 'Auth'
], function () {
    // Authentication Routes...
    $this->get('login', 'LoginController@showLoginForm')->name('login');
    $this->post('login', 'LoginController@login');
    $this->post('logout', 'LoginController@logout')->name('logout');

    $this->get('admin/login', 'AdminController@showLoginForm')->name('admin.login');
    $this->post('admin/login', 'AdminController@login')->name('admin.login');

    // Registration Routes...
    $this->get('register', 'RegisterController@showRegistrationForm')->name('register');
    $this->post('register', 'RegisterController@register');

    //verification Email
    $this->get('/verifyemail/{token}', 'RegisterController@verify');

    // Password Reset Routes...
    $this->get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    $this->post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    $this->get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    $this->post('password/reset', 'ResetPasswordController@reset');
});


// Admin Route
Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => 'auth.check:admin'
], function (){
    $this->get('/', 'DashboardController@index');
    $this->get('/pengaturan', 'SettingController@index')->name('setting');
    $this->post('/pengaturan/update', 'SettingController@update')->name('setting.update');
    $this->post('/pengaturan/avatar', 'SettingController@updateAvatar')->name('setting.avatar');
    $this->get('/logout', function () {
        \Illuminate\Support\Facades\Auth::logout();
        return redirect('/');
    })->name('logout');

    $this->group([
        'prefix' => '/destinasi',
    ], function () {
        $this->get('/', 'DestinationController@index')->name('destinasi');
        $this->get('/tambah', 'DestinationController@create')->name('destinasi.create');
        $this->post('/store', 'DestinationController@store')->name('destinasi.store');
        $this->get('/{slug}/edit', 'DestinationController@edit')->name('destinasi.edit');
        $this->post('/{slug}/update', 'DestinationController@update')->name('destinasi.update');
        $this->delete('/{slug}/delete', 'DestinationController@destroy')->name('destinasi.delete');
        $this->post('/{slug}/status', 'DestinationController@status')->name('destinasi.status');
    });

    $this->group([
        'prefix' => '/galeri',
    ], function () {
        $this->get('/', 'GalleryController@index')->name('galeri');
        $this->get('/tambah', 'GalleryController@create')->name('galeri.create');
        $this->post('/store', 'GalleryController@store')->name('galeri.store');
        $this->get('/{slug}/edit', 'GalleryController@edit')->name('galeri.edit');
        $this->post('/{slug}/update', 'GalleryController@update')->name('galeri.update');
        $this->delete('/{slug}/delete', 'GalleryController@destroy')->name('galeri.delete');
        $this->post('/{slug}/status', 'GalleryController@status')->name('galeri.status');
    });

    $this->group([
        'prefix' => '/event',
    ], function () {
        $this->get('/', 'EventController@index')->name('event');
        $this->get('/tambah', 'EventController@create')->name('event.create');
        $this->post('/store', 'EventController@store')->name('event.store');
        $this->get('/{slug}/edit', 'EventController@edit')->name('event.edit');
        $this->post('/{slug}/update', 'EventController@update')->name('event.update');
        $this->delete('/{slug}/delete', 'EventController@destroy')->name('event.delete');
        $this->post('/{slug}/status', 'EventController@status')->name('event.status');
    });

    $this->group([
        'prefix' => '/kuliner',
    ], function () {
        $this->get('/', 'CulinaryController@index')->name('kuliner');
        $this->get('/tambah', 'CulinaryController@create')->name('kuliner.create');
        $this->post('/store', 'CulinaryController@store')->name('kuliner.store');
        $this->get('/{slug}/edit', 'CulinaryController@edit')->name('kuliner.edit');
        $this->post('/{slug}/update', 'CulinaryController@update')->name('kuliner.update');
        $this->delete('/{slug}/delete', 'CulinaryController@destroy')->name('kuliner.delete');
        $this->post('/{slug}/status', 'CulinaryController@status')->name('kuliner.status');
    });
});

Route::group([
    'namespace' => 'Member',
    'middleware' => 'auth.check:member',
    'prefix' => '/home',
    'as' => 'member.',
], function () {
    $this->get('/', 'DashboardController@index');
    $this->get('/pengaturan', 'SettingController@index')->name('setting');
    $this->post('/pengaturan/update', 'SettingController@update')->name('setting.update');
    $this->post('/pengaturan/avatar', 'SettingController@updateAvatar')->name('setting.avatar');
    $this->get('/logout', function () {
        \Illuminate\Support\Facades\Auth::logout();
        return redirect('/');
    })->name('logout');

    $this->group([
        'prefix' => '/destinasi',
    ], function () {
        $this->get('/', 'DestinationController@index')->name('destinasi');
        $this->get('/tambah', 'DestinationController@create')->name('destinasi.create');
        $this->post('/store', 'DestinationController@store')->name('destinasi.store');
        $this->get('/{slug}/edit', 'DestinationController@edit')->name('destinasi.edit');
        $this->post('/{slug}/update', 'DestinationController@update')->name('destinasi.update');
        $this->delete('/{slug}/delete', 'DestinationController@destroy')->name('destinasi.delete');
    });

    $this->group([
        'prefix' => '/galeri',
    ], function () {
        $this->get('/', 'GalleryController@index')->name('galeri');
        $this->get('/tambah', 'GalleryController@create')->name('galeri.create');
        $this->post('/store', 'GalleryController@store')->name('galeri.store');
        $this->get('/{slug}/edit', 'GalleryController@edit')->name('galeri.edit');
        $this->post('/{slug}/update', 'GalleryController@update')->name('galeri.update');
        $this->delete('/{slug}/delete', 'GalleryController@destroy')->name('galeri.delete');
    });

    $this->group([
        'prefix' => '/event',
    ], function () {
        $this->get('/', 'EventController@index')->name('event');
        $this->get('/tambah', 'EventController@create')->name('event.create');
        $this->post('/store', 'EventController@store')->name('event.store');
        $this->get('/{slug}/edit', 'EventController@edit')->name('event.edit');
        $this->post('/{slug}/update', 'EventController@update')->name('event.update');
        $this->delete('/{slug}/delete', 'EventController@destroy')->name('event.delete');
    });

    $this->group([
        'prefix' => '/kuliner',
    ], function () {
        $this->get('/', 'CulinaryController@index')->name('kuliner');
        $this->get('/tambah', 'CulinaryController@create')->name('kuliner.create');
        $this->post('/store', 'CulinaryController@store')->name('kuliner.store');
        $this->get('/{slug}/edit', 'CulinaryController@edit')->name('kuliner.edit');
        $this->post('/{slug}/update', 'CulinaryController@update')->name('kuliner.update');
        $this->delete('/{slug}/delete', 'CulinaryController@destroy')->name('kuliner.delete');
    });
});

app/Http/Controllers/Admin/EventController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Jobs\Contents\CreateContent;
use App\Jobs\Contents\DeleteContent;
use App\Jobs\Contents\UpdateContent;
use App\Models\Contents\Content;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class EventController extends Controller
{
    protected $type = 'event';

    public function __construct()
    {
        $this->middleware('auth.check:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $events = Content::where('type', '=', $this->type)->paginate(10);

        $data = [
            'event' => $events
        ];

        return view('admin.events.index', $data);
    }

    /**
     * Show the form for creating a new
     * resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.events.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'description' => 'required',
            'images.*' => 'required|image|mimes:jpeg,png,jpg,gif,svg',
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator->errors());
        }

        $request->type = $this->type;

        try {
            $this->dispatch(new CreateContent($request));
        } catch (\Exception $exception) {
            return redirect()->back()->withErrors($exception);
        }

        return redirect()->route('admin.event')->with('success', 'Event berhasil dibuat');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $slug
     * @return void
     */
    public function edit($slug)
    {
        $event = Content::where('type', '=', $this->type)
            ->where('slug', '=', $slug)->first();

        if ($event->count() == 0) {
            return redirect()->back()->withErrors('Event tidak ada');
        }

        $date_start = explode('-', $event->date_start);

        $data = [
            'event' => $event,
            'date' => $date_start,
        ];

        return view('admin.events.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param $slug
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $slug)
    {
        $event = Content::where('type', '=', $this->type)
            ->where('slug', '=', $slug)->first();

        if ($event->count() == 0) {
            return redirect()->back()->withErrors('Event tidak ada');
        }

        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'description' => 'required',
            'date_start.*' => 'required|string',
        ]);

        if ($validator->fails()) {
            return back()->with($validator->errors());
        }

        try {
            $this->dispatch(new UpdateContent($request, $event));
        } catch (\Exception $exception) {
            return redirect()->back()->withErrors('Event not found');
        }

        return redirect()->route('admin.event')->with('success', 'Berhasil di update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($slug)
    {
        $event = Content::where('type', '=', $this->type)
            ->where('slug', '=', $slug)->first();

        if ($event->count() == 0) {
            return redirect()->back()->withErrors('Event tidak ada');
        }

        try {
            $this->dispatch(new DeleteContent($event));
        } catch (\Exception $exception) {
            return redirect()->back()->withErrors('Event tidak ada');
        }

        return redirect()->route('admin.event')->with('success' ,'Berhasil di hapus');
    }

    public function status($slug, Request $request)
    {
        $event = Content::where('type', '=', $this->type)
            ->where('slug', '=', $slug)->first();

        try {
            $event->status = $request->status;
            $event->save();
        } catch (\Exception $exception) {
            return back()->withErrors(['error' => $exception]);
        }

        return redirect()->route('admin.event')->with('success', 'Status telah diperbarui');
    }
}

app/Http/Controllers/Member/DashboardController.php
<?php

namespace App\Http\Controllers\Member;

use App\Http\Controllers\Controller;
use App\Models\Contents\Article;
use App\Models\Contents\Content;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth.check:member');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $destination = Article::where('type', '=', 'destination')
            ->where('user_id', '=', Auth()->user()->id)->count();
        $culinary = Content::where('type', '=', 'culinary')
            ->where('user_id', '=', Auth()->user()->id)->count();
        $gallery = Content::where('type', '=', 'gallery')
            ->where('user_id', '=', Auth()->user()->id)->count();
        $event = Content::where('type', '=', 'event')
            ->where('user_id', '=', Auth()->user()->id)->count();

        $data = [
            'destination' => $destination,
            'culinary' => $culinary,
            'gallery' => $gallery,
            'event' => $event,
        ];

        return view('member.index', $data);
    }
}

app/Http/Controllers/Member/SettingController.php
<?php
/**
 * Created by PhpStorm.
 * User: ANDROMEDA
 * Date: 4/17/2018
 * Time: 7:18 PM
 */

namespace App\Http\Controllers\Member;


use App\Http\Controllers\Controller;
use App\Jobs\Media\CreateMedia;
use App\Jobs\Media\DeleteAllMedia;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class SettingController extends Controller
{
    public function index()
    {
        $user = Auth()->user();

        $data = [
            'user' => $user
        ];

        return view('admin.settings', $data);
    }

    public function update(Request $request)
    {
        $user = Auth()->user();

        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'username' => 'required',
            'email' => 'required|string|email',
            'password' => 'required'
        ]);

        if ($validator->fails() == true) {
            return redirect()->back()->withErrors($validator->errors());
        }

        if (password_verify($request->password, $user->password)) {
            try {
                $user->name = $request->name;
                $user->username = $request->username;
                $user->email = $request->email;

                $user->save();
            } catch (\Exception $exception) {
                return redirect()->back()->withErrors('Something errors');
            }

            return redirect()->route('admin.setting')->with('success', 'Data berhasil di update');
        } else {
            return redirect()->back()->withErrors('Password tidak sama');
        }
    }

    public function updateAvatar(Request $request)
    {
        $user = Auth()->user();

        $validator = Validator::make($request->all(), [
            'avatar.*' => 'required|image|mimes:jpeg,png,jpg,gif,svg',
        ]);

        if ($validator->fails() == true) {
            return redirect()->back()->withErrors($validator->errors());
        }

        try {
            $this->dispatch(new DeleteAllMedia($user));
            $this->dispatch(new CreateMedia($user, $request));
        } catch (\Exception $exception) {
            return redirect()->back()->withErrors('Something errors');
        }

        return redirect()->route('admin.setting')->with('success', 'Avatar berhasil di update');
    }
}

resources/views/member/events/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: ANDROMEDA
 * Date: 4/3/2018
 * Time: 8:32 PM
 */
?>
@extends('member.layouts.app')
@section('content')
    <div class="container">
        <div class="content" style="float:left; padding: 0; width:100%">
            <h2 style="margin-left:22px">Buat Event</h2>
            @foreach($errors->all() as $error)
                <div class="notification">
                    <div class="alert alert-danger">
                        {{ $error }}
                    </div>
                </div>
            @endforeach
            <form class="form" action="{{ Route('member.event.store') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="group">
                    <label for="title">Judul <span class="required">*</span></label>
                    <input id="title" class="input-field input-field-long" type="text" name="title" required>
                    <label for="images.0">Gambar <span class="required">*</span></label>
                    <input id="images.0" class="input-field" type="file" name="images[]" multiple required>
                </div>
                <div class="group">
                    <label for="date_start.">Tanggal Mulai <span class="required">*</span></label>
                    <select name="date_start[]" id="date_start." style="color: #000;">
                        <option value="">Tanggal</option>
                        @for($d=1; $d<=31; $d++)
                            <option value="{{ $d }}">
                                {{ $d }}
                            </option>
                        @endfor
                    </select>
                    <select name="date_start[]" id="date_start." style="color: #000;">
                        <option value="">Bulan</option>
                        @for($m=0; $m<=11; $m++)
                            <option value="{{ date('F', strtotime("$m month"))}}">
                                {{ date('F', strtotime("+$m month"))}}
                            </option>
                        @endfor
                    </select>
                    <select name="date_start[]" id="date_start." style="color: #000;">
                        <option value="">Tahun</option>
                        @for($y=0; $y<=5; $y++)
                            <option value="{{ date('Y', strtotime("last day of +$y year")) }}">
                                {{ date('Y', strtotime("last day of +$y year")) }}
                            </option>
                        @endfor
                    </select>
                </div>
                <div class="group-full">
                  <label for="description">Deskripsi <span class="required">*</span></label>
                  <textarea name="description" id="description" class="input-field input-field-long"
                            required></textarea>
                </div>
                <div class="group-full" style="text-align: center; margin-top:12px;">
                    <button class="btn green" type="submit" style="text-align: center">Save</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/member/events/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: ANDROMEDA
 * Date: 4/3/2018
 * Time: 8:32 PM
 */
?>
@extends('member.layouts.app')
@section('content')
    <div class="container">
        <div class="content" style="float:left; padding: 0; width:100%">
            <h2 style="margin-left:22px">Edit Event</h2>
            @foreach($errors->all() as $error)
                <div class="notification">
                    <div class="alert alert-danger">
                        {{ $error }}
                    </div>
                </div>
            @endforeach
            <form class="form" action="{{ Route('member.event.update', $event->slug) }}" method="post"
                  enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="group">
                    <label for="title">Judul <span class="required">*</span></label>
                    <input id="title" class="input-field input-field-long" type="text" name="title"
                           value="{{ $event->title }}" required>
                    <label for="description">Deskripsi <span class="required">*</span></label>
                    <textarea name="description" id="description" class="input-field input-field-long"
                              required>{{ $event->description }}</textarea>
                </div>
                <div class="group">
                    <select name="date_start[]" id="date_start." style="color: #000;">
                        <option value="">Tanggal</option>
                        @for($d=1; $d<=31; $d++)
                            <option value="{{ $d }}"
                                @if($d == $date[0])
                                    {{ "SELECTED" }}
                                @endif
                            >
                                {{ $d }}
                            </option>
                        @endfor
                    </select>
                    <select name="date_start[]" id="date_start." style="color: #000;">
                        <option value="">Bulan</option>
                        @for($m=0; $m<=11; $m++)
                            <option value="{{ date('F', strtotime("+$m month")) }}"
                                @if(date('F', strtotime("+$m month")) == $date[1])
                                    {{ "SELECTED" }}
                                @endif
                            >
                                {{ date('F', strtotime("+$m month"))}}
                            </option>
                        @endfor
                    </select>
                    <select name="date_start[]" id="date_start." style="color: #000;">
                        <option value="">Tahun</option>
                        @for($y=0; $y<=5; $y++)
                            <option value="{{ date('Y', strtotime("last day of +$y year")) }}"
                                @if(date('Y', strtotime("last day of +$y year")) == $date[2])
                                    {{ "SELECTED" }}
                                @endif
                            >
                                {{ date('Y', strtotime("last day of +$y year")) }}
                            </option>
                        @endfor
                    </select>
                </div>
                <div class="group">
                    <button class="btn green" type="submit" style="text-align: center">Save</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/member/events/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: ANDROMEDA
 * Date: 4/3/2018
 * Time: 8:25 PM
 */
?>
@extends('member.layouts.app')
@section('content')
    <div class="container">
        <div class="content content-table">
            @if(session('success'))
                <div class="notification">
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                </div>
            @endif
            <div class="top">
                <span style="float:left"><h1>Event</h1></span>
                <a href="{{ route('member.event.create') }}" class="btn btn-small blue"
                   style="margin: 20px; float:left">Tambah</a>
            </div>
            <table class="table">
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Status</th>
                    <th>Author</th>
                    <th>Gambar</th>
                    <th>Aksi</th>
                </tr>
                @foreach($event as $key => $value)
                    <tr>
                        <td>{{ $key+1 }}</td>
                        <td>{{ $value->title }}</td>
                        <td>
                            @if($value->slug == 'published')
                                <span class="badge badge-success">Published</span>
                            @else
                                <span class="badge badge-warning">Pending</span>
                            @endif
                        </td>
                        <td>{{ $value->user->name }}</td>
                        <td>{{ $value->media()->count() }}</td>
                        <td width="255">
                            <a href="{{ route('member.event.edit', $value->slug) }}" class="btn blue"
                               style="float:left">Edit</a>
                            <a href="#" class="btn green" style="float:left; margin-left:5px">Lihat</a>
                            <span style="float:left; margin-left:5px">
                          <form class="" action="{{ route('member.event.delete', $value->slug) }}" method="post">
                              {{ csrf_field() }}
                              {{ method_field('DELETE') }}
                              <button type="submit" class="btn red">Hapus</button>
                          </form>
                        </span>
                        </td>
                    </tr>
                @endforeach
            </table>
            {{ $event->links('vendor.pagination.paging') }}
        </div>
    </div>
@endsection